name: ADLS Access via Managed Identity Federation

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required to request OIDC token
  contents: read

jobs:
  access-adls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure using federated credential
        run: |
          az login --federated-token $ACTIONS_ID_TOKEN --allow-no-subscriptions --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }}
        env:
          ACTIONS_ID_TOKEN: ${{ steps.oidc-token.outputs.token }}
      - name: Get OIDC token
        id: oidc-token
        run: echo "::set-output name=token::${{ steps.get_token.outputs.id_token }}"

      - name: Access ADLS
        run: |
          az storage blob list --account-name <storage-account-name> --container-name <container-name> --auth-mode login
